//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVXK.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int idDonHang { get; set; }
        public int idVeXe { get; set; }
        public int idXe { get; set; }
        public int idLichTrinh { get; set; }
        public string tenKhachHang { get; set; }
        public string soDienThoai { get; set; }
        public Nullable<System.DateTime> thoiGianDon { get; set; }
        public string diemDon { get; set; }
        public string diemTra { get; set; }
        public Nullable<decimal> tongTien { get; set; }
        public Nullable<int> tinhTrang { get; set; }
    
        public virtual LichTrinh LichTrinh { get; set; }
        public virtual VeXe VeXe { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
