//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVXK.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichTrinh()
        {
            this.DonHang = new HashSet<DonHang>();
        }
    
        public int idLichTrinh { get; set; }
        public int idXe { get; set; }
        public string noiXuatPhat { get; set; }
        public string noiDen { get; set; }
        public Nullable<System.DateTime> ngayDi { get; set; }
        public Nullable<System.DateTime> ngayDen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
