//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVXK.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeXe()
        {
            this.DonHang = new HashSet<DonHang>();
        }
    
        public int idVe { get; set; }
        public int idXe { get; set; }
        public int idLichTrinh { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<int> tinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
